### PR TITLE
[6.16] Single driver for nt36672a based panels + nvt-ts fixes

### LINKED ISSUE #70: Add real panel driver for lavender and panel-follower mode for nvt-ts
novatek touchscreen driver needs to learn how to be a panel follower.

Examples of adding support to be a panel follower:

Already in mainline:
* 96a37bfd232ae912648c73cd2dc29c13f1c7776a, 76edfcf430cc2fa1abcfb910a2643eed102a1590

From adomerle:
* https://github.com/pipa-mainline/linux/commit/61a746918fc541b60231432e55f63ed99342a74a
* https://github.com/pipa-mainline/linux/commit/4bfd6550fbfed44c3f43fb9a85729f39836f3efd

### PR DESCRIPTION
**Pull request by minlexx**
* Modernize panel-novatek-nt36672a driver
* Refactor panel-novatek-nt36672a driver to allow for easier extension
* Add panel drivers for:
  * xiaomi-lavender-tianma
  * xiaomi-lavender-shenchao
  * xiaomi-tulip
  * xiaomi-jasmine_sprout
  * asus-x00td
* switch aforementioned devices to new panel driver 
* switch aforementioned devices to nvt-ts touch driver
* add panel-follower mode support to nvt-ts driver
* new dts for xiaomi-lavender-shenchao
* dt-bindings patches for all of the above :see_no_evil: 

Perhaps we can now drop nt36xxx touch driver?

Fixes #70

### CODE REVIEW

**Comment by minlexx** [comment]
I'm thinking if lavender-shenchao panel init sequence is very similar to lavender-tianma one, they all should be squashed into one commit (with tulip's panel also). That would be the last optimization here, also maybe try different workaround from issue #91 and drop the last HACK commit from this MR, and that's all TODO..

**Comment by minlexx** [comment]
Removed HACK for this panel to move sending DSI commands from `.unprepare` to `.disable` since 345116231b31e1ad64b9f599efd2797daaae7318 is in base branch now.

On jasmine nvt-ts is spamming ~10 times per second with
```
[  266.950386] novatek-nvt-ts 0-0001: slot 14 out of range, ignoring
[  266.956424] novatek-nvt-ts 0-0001: slot 14 out of range, ignoring
[  266.962468] novatek-nvt-ts 0-0001: slot 14 out of range, ignoring
```
:cry:

**Comment by minlexx** [comment]
```
[    6.046068] novatek-nvt-ts 0-0001: Detected 1080x2160 touchscreen with 10 max touches
```
14 is definitely out of range then :thinking:

File: drivers/gpu/drm/panel/panel-novatek-nt36672a.c [hunk 1]
```diff
@@ -79,23 +71,740 @@ static inline struct nt36672a_panel *to_nt36672a_panel(struct drm_panel *panel)
...
+	mipi_dsi_dcs_write_seq_multi(&dsi_ctx, 0xff, 0x10);
+
+	mipi_dsi_dcs_exit_sleep_mode_multi(&dsi_ctx);
+	mipi_dsi_msleep(&dsi_ctx, 80);
+
+	mipi_dsi_dcs_write_seq_multi(&dsi_ctx, 0xb0, 0x01);
+	mipi_dsi_dcs_set_tear_on_multi(&dsi_ctx, MIPI_DSI_DCS_TEAR_MODE_VBLANK);
+
+	if (of_device_is_compatible(dev_of_node(&pinfo->link->dev),
+				    "novatek,nt36672a-tianma-lavender")) {
```
Comment (minlexx) [inline drivers/gpu/drm/panel/panel-novatek-nt36672a.c]: The check for compatible string here is now incorrect, should be "tianma,tl063fvmca01-00" (lavender-tianma panel still worked though :laughing:  )

3 panels (lavender-tianma, lavender-shenchao, tulip) can and probaly should use the same init function, and be added in a one single commit in preparation for submission upstream.

Comment (minlexx) [reply drivers/gpu/drm/panel/panel-novatek-nt36672a.c]: This is now fixed - compatibles are now checked differently.

Separate init function for lavender-shenchao panel is gone. One single init function handles 3 panels (2 for lavender, 1 for tulip), all are added in one single commit.

**Comment by minlexx** [comment]
> Perhaps we can now drop nt36xxx touch driver?

Damn platina...
```
$ grep -rn novatek,nt36525 ./arch/
../arch/arm64/boot/dts/qcom/sdm660-xiaomi-platina.dts:257:              compatible = "novatek,nt36525";
```

**Comment by minlexx** [comment]
The latest 6 revert commits remove drivers that are now not necessary:
* the old nt36xxx novatek touch driver from Angelo
* separate panel driver for jasmine
* separate panel driver for x00td
* panel-simple addition for tulip
* panel-simple addition for lavender

Additionally, they are removed from `sdm660_defconfig`

This now looks ready? Few final tests from me on lavender and jasmine..

**Comment by minlexx** [comment]
Works on my devices, and @iAboothahir tested on x00td, so hopefully nothing explodes on others :laughing: 

Allahu Akbar

File: drivers/gpu/drm/panel/panel-novatek-nt36672a.c [hunk 2]
```diff
@@ -79,23 +71,342 @@ static inline struct nt36672a_panel *to_nt36672a_panel(struct drm_panel *panel)
...
+static int tianma_beryllium_init_cmds(struct drm_panel *panel)
 {
 	struct nt36672a_panel *pinfo = to_nt36672a_panel(panel);
-	unsigned int i;
-	int err;
+	struct mipi_dsi_multi_context dsi_ctx = { .dsi = pinfo->link };
+
+	/* send first part of init cmds (.on_cmds_1) */
+	/* skin enhancement mode */
+	mipi_dsi_dcs_write_seq_multi(&dsi_ctx, 0xFF, 0x22);
```
Comment (lumag) [inline drivers/gpu/drm/panel/panel-novatek-nt36672a.c:81]: Nit: lowercase the hex for the upstream submission.
